services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Personnel\DataProcessing\PersonnelDatabaseQueryProcessor:
    public: true

  Brightside\Personnel\ViewHelpers\ImageViewHelper:
    public: true
